const HTTP_CREATED = 201;
const HTTP_NO_CONTENT = 204;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHENTICATED = 401;
const HTTP_UNAUTHORIZED = 403;
const HTTP_NOT_FOUND = 404;

export {
  HTTP_BAD_REQUEST,
  HTTP_CREATED,
  HTTP_NO_CONTENT,
  HTTP_NOT_FOUND,
  HTTP_UNAUTHENTICATED,
  HTTP_UNAUTHORIZED,
};
