// dummy data
const championStats = [
  {
    type: "ranked",
    champions: [
      {
        champion: "Ekko",
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
      {
        champion: "Syndra",
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
      {
        champion: "Renekton",
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
      {
        champion: "Annie",
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
      {
        champion: "Xerath",
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
      {
        champion: "Orianna",
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
      {
        champion: "Galio",
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
      {
        champion: "Garen",
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
      {
        champion: "Viktor", // this champ shouldn't be shown because there are already max number of champions shown
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
    ],
  },
  {
    type: "normal",
    champions: [
      {
        champion: "Lucian",
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
      {
        champion: "MonkeyKing",
        csTotal: 178.6,
        kills: 7,
        deaths: 3,
        assists: 17,
        wr: 58,
        games: 137,
      },
    ],
  },
  {
    type: "others",
    champions: [],
  },
];

export default championStats;
